# Generated by Django 5.1.1 on 2024-09-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_classes_class101_rename_courses_course'),
        ('students', '0002_rename_student_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
